### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by telephant00**
I love Harvest almost 100% as-is, but I wonder if this configuration would be more friendly to the idea of getting up and running fast and with no fuss. Using BrowserSync instead of LiveReload frees you up from having to install a browser extension and includes a ton of great options, easily configurable. What do you think?

### CODE REVIEW

**Comment by ryanbenson** [comment]
That's a great idea! If there's a way to make it easier, I'm all for it.

I pulled in your changes, but I'm getting a couple weird things:
* Segfault errors: 85049 segmentation fault gulp
* I disabled the notification that popped up on every refresh, but that seemed to make the segfault errors worse

Are you getting those seg faults too?

**Comment by telephant00** [comment]
That's weird for sure. I just double checked everything and I'm not experiencing those errors, nor have I ever.

**Comment by telephant00** [comment]
Just out of curiosity, did you make sure to `sudo npm install` again after pulling in my new package.json file?

**Comment by ryanbenson** [comment]
Odd that you're not getting any of the errors. I installed everything using sudo. I'm running Yosemite 10.10.2 and Node 0.12.0.  I'll try to update some things and try it again.

**Comment by telephant00** [comment]
I realized I was running Node v0.10 something or other. I updated to the latest version of Node, v0.12.2. Then I had to upgrade node-sass as well. This is the new commit for that. Works great for me. Try it out and see.

**Comment by jkrot** [comment]
Running Yosemite 10.10.2 as well I did not need to run sudo npm install because I have my folder permissions setup correctly.  No Errors after the node-sass update.  I was already running on Node 0.12 so didn't give me an issue.

**Comment by ryanbenson** [comment]
I figured it out! It was gulp-imagemin that was giving me issues. I updated it, and somehow my image task got messed up. Once I fixed that, everything worked as expected. Thanks for your help. I'll merge this in :) I'll also add in the `notify: false` property for BrowserSync to hide the pop up messages.

Thanks again guys and great idea :)

**Comment by telephant00** [comment]
Great to hear!

**Pull request merged**
